; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ros1]
platform = atmelsam
board = due
framework = arduino

monitor_port = /dev/ttyACM0
monitor_speed = 115200

build_src_filter =
  -<src/ros2_main.cpp>
  -<src/serial_main.cpp>

;upload_port = /dev/ttyACM0
;upload_speed = 57600

lib_deps =
    frankjoshua/Rosserial Arduino Library @ 0.9.1
    hideakitai/MPU9250 @ ^0.4.6

[env:ros2]
platform = atmelsam
board = due
framework = arduino

monitor_port = /dev/ttyACM0
monitor_speed = 115200

build_src_filter =
  +<*.cpp>
  -<ros1_main.cpp>
  -<serial_main.cpp>

board_microros_transport = serial
board_microros_distro = kilted

upload_port = /dev/ttyACM0
upload_speed = 250000

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    hideakitai/MPU9250 @ ^0.4.6

[env:serial]
platform = atmelsam
board = due
framework = arduino

monitor_port = /dev/ttyACM0
monitor_speed = 115200

build_src_filter =
  +<*.cpp>
  -<ros1_main.cpp>
  -<ros2_main.cpp>

upload_port = /dev/ttyACM0
upload_speed = 250000

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0
    hideakitai/MPU9250 @ ^0.4.6
